add raw-scripts-traced rust crate (#197)
* add raw-scripts-traced rust crate

* refactor .cabal file to not use custom flags

* update changelog

diff --git a/onchain/Makefile b/onchain/Makefile
--- a/onchain/Makefile
+++ b/onchain/Makefile
@@ -2,6 +2,7 @@ all: onchain check-raw-scripts
 
 onchain-dir := ../onchain/
 trustless-sidechain-serialise=cabal run trustless-sidechain-serialise --
+trustless-sidechain-serialise-traced=cabal run trustless-sidechain-serialise-traced --
 # Haskell source dependencies include shared Prelude libraries and the
 # serialization binary
 haskell-scripts := $(shell find $(onchain-dir)/src -type f -name "*.hs") \
@@ -9,6 +10,7 @@ haskell-scripts := $(shell find $(onchain-dir)/src -type f -name "*.hs") \
                    $(shell find $(onchain-dir)/app/serialise -type f -name "*.hs")
 # Output files with serialized scripts
 raw-scripts-rs := ../raw-scripts/src/lib.rs
+raw-scripts-rs-trace := ../raw-scripts-traced/src/lib.rs
 
 onchain:
 	cabal update
@@ -17,9 +19,16 @@ onchain:
 
 update-scripts: ${raw-scripts-rs}
 
+update-scripts-trace: ${raw-scripts-rs-trace}
+
 ${raw-scripts-rs}: ${haskell-scripts}
 	@echo 'Generating `$@`...'
 	${trustless-sidechain-serialise} --rust-plutus-scripts=${CURDIR}/${raw-scripts-rs}
+	@echo 'Updated `$@`.'
+
+${raw-scripts-rs-trace}: ${haskell-scripts}
+	@echo 'Generating `$@`...'
+	${trustless-sidechain-serialise-traced} --rust-plutus-scripts=${CURDIR}/${raw-scripts-rs-trace}
 	@echo 'Updated `$@`.'
 
 check-raw-scripts:
@@ -27,6 +36,14 @@ check-raw-scripts:
 	@if ! git diff --quiet -- ../raw-scripts/src/lib.rs ; then \
 	  echo \
 	  echo "Error: raw-scripts/src/lib.rs is not up to date"; \
+	  echo \
+	  exit 1; \
+	fi
+
+	@make -B update-scripts-trace
+	@if ! git diff --quiet -- ../raw-scripts/src/lib-trace.rs ; then \
+	  echo \
+	  echo "Error: raw-scripts-traced/src/lib.rs is not up to date"; \
 	  echo \
 	  exit 1; \
 	fi
