Simplify Makefile
* No need to track haskell sources. The whole build is essentially a PHONY
target so it is better to simply rely on cabal for (re-)building

* Use Makefile variables instead of repeating names where applicable

* Fix bug in update-scripts target: lib.rs vs lib-traced.rs

* Do not call `cabal update` as we don't want to have changing
  dependencies in CI builds

diff --git a/onchain/Makefile b/onchain/Makefile
--- a/onchain/Makefile
+++ b/onchain/Makefile
@@ -1,49 +1,39 @@
+.PHONY: all onchain update-scripts update-scripts-trace check-raw-scripts
+
+trustless-dir := ../raw-scripts
+trustless-traced-dir := ../raw-scripts-traced
+
+serialise        := cabal run trustless-sidechain-serialise --
+serialise-traced := cabal run trustless-sidechain-serialise-traced --
+
+raw-scripts := $(trustless-dir)/src/lib.rs
+raw-scripts-trace := $(trustless-traced-dir)/src/lib.rs
+
 all: onchain check-raw-scripts
 
-onchain-dir := ../onchain/
-trustless-sidechain-serialise=cabal run trustless-sidechain-serialise --
-trustless-sidechain-serialise-traced=cabal run trustless-sidechain-serialise-traced --
-# Haskell source dependencies include shared Prelude libraries and the
-# serialization binary
-haskell-scripts := $(shell find $(onchain-dir)/src -type f -name "*.hs") \
-	                 $(shell find $(onchain-dir)/prelude -type f -name "*.hs") \
-                   $(shell find $(onchain-dir)/app/serialise -type f -name "*.hs")
-# Output files with serialized scripts
-raw-scripts-rs := ../raw-scripts/src/lib.rs
-raw-scripts-rs-trace := ../raw-scripts-traced/src/lib.rs
-
 onchain:
-	cabal update
 	cabal build
 	cabal test all --test-show-details=direct
 
-update-scripts: ${raw-scripts-rs}
+update-scripts:
+	@echo "Generating $(raw-scripts)..."
+	$(serialise) --rust-plutus-scripts=$$PWD/$(raw-scripts)
+	@echo "Updated $(raw-scripts)."
 
-update-scripts-trace: ${raw-scripts-rs-trace}
-
-${raw-scripts-rs}: ${haskell-scripts}
-	@echo 'Generating `$@`...'
-	${trustless-sidechain-serialise} --rust-plutus-scripts=${CURDIR}/${raw-scripts-rs}
-	@echo 'Updated `$@`.'
-
-${raw-scripts-rs-trace}: ${haskell-scripts}
-	@echo 'Generating `$@`...'
-	${trustless-sidechain-serialise-traced} --rust-plutus-scripts=${CURDIR}/${raw-scripts-rs-trace}
-	@echo 'Updated `$@`.'
+update-scripts-trace:
+	@echo "Generating $(raw-scripts-trace)..."
+	$(serialise-traced) --rust-plutus-scripts=$$PWD/$(raw-scripts-trace)
+	@echo "Updated $(raw-scripts-trace)."
 
 check-raw-scripts:
-	@make -B update-scripts
-	@if ! git diff --quiet -- ../raw-scripts/src/lib.rs ; then \
-	  echo \
-	  echo "Error: raw-scripts/src/lib.rs is not up to date"; \
-	  echo \
-	  exit 1; \
+	@$(MAKE) update-scripts
+	@if ! git diff --quiet -- $(raw-scripts); then \
+		echo "\nError: $(raw-scripts) is not up to date\n"; \
+		exit 1; \
 	fi
 
-	@make -B update-scripts-trace
-	@if ! git diff --quiet -- ../raw-scripts/src/lib-trace.rs ; then \
-	  echo \
-	  echo "Error: raw-scripts-traced/src/lib.rs is not up to date"; \
-	  echo \
-	  exit 1; \
+	@$(MAKE) update-scripts-trace
+	@if ! git diff --quiet -- $(raw-scripts-trace); then \
+		echo "\nError: $(raw-scripts-trace) is not up to date\n"; \
+		exit 1; \
 	fi
