Remove some shell oddities

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -3,15 +3,17 @@ set +e
 
 die() {
 	code=$?
-	echo $* >&2 && exit $code
+	echo "$@" >&2 && exit $code
 }
 
 check() {
-	command -v $1 >/dev/null \
+	command -v "$1" >/dev/null \
 		|| die "please enter a shell environment where \`$1\` is present," \
 		       "then commit your changes."
-	$*
-    [ "$?" -eq "0" ] || die 'ERROR: precommit hook failed. Running `make format-staged && git add .` in the project root may fix this'
+	# Note from Koz: This is intentionally designed to split into multiple
+  # pieces, so please don't panic-quote it.
+  $* \
+    || die "ERROR: precommit hook failed. Running \`make format-staged && git add .\` in the project root may fix this"
 }
 
 # If there are whitespace errors, print the offending file names and fail.
